### ISSUE TITLE
Errore plugin.video.rivedila7/addon.py 1.0.0 - funzione rivedi_la7_giorno

### ISSUE THREAD

**Issue by tpwrm** [luivit/plugin.video.rivedila7#15]
Ciao a tutti,

probabilmente a fronte di un errore nell'html di [rivedila7](http://www.la7.it/rivedila7/2/LA7) il plugin ha smesso di funzionare. Praticamente nel div class="descrizione" non è sempre presente il tag p.

L'errore riscontrato è a riga 114 di plugin.video.rivedila7/addon.py, funzione rivedi_la7_giorno:

```
23:00:12.598 T:2539647744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'contents'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.rivedila7/addon.py", line 215, in <module>
                                                rivedi_la7_giorno()
                                              File "/home/osmc/.kodi/addons/plugin.video.rivedila7/addon.py", line 114, in rivedi_la7_giorno
                                                plot=div.find('div',class_='descrizione').p.contents[0]
                                            AttributeError: 'NoneType' object has no attribute 'contents'
                                            -->End of Python script error report<--
```

Io al momento ho risolto così:

```
def rivedi_la7_giorno():
    req = urllib2.Request(url_base+giorno,headers=headers) 
    page=urllib2.urlopen(req)
    html=BeautifulSoup(page,'html5lib')
    guida_tv=html.find(id="content_guida_tv").find_all('div' ,class_='disponibile')
    if guida_tv is not None:
        for div in guida_tv:
            nome=div.find('div',class_='titolo clearfix').a.contents[0].encode('utf-8')
            thumb=div.find('img')['src']
           # plot=div.find('div',class_='descrizione').p.contents[0]
            plot=div.find('div',class_='descrizione').get_text()
            urll=div.find('div',class_='titolo').a.get('href')
            orario=div.find('div',class_='orario').contents[0].encode('utf-8')
            liStyle = xbmcgui.ListItem(orario+" "+nome)
            liStyle.setArt({ 'thumb': thumb})
            liStyle.setInfo('video', { 'plot': plot })
            url2 = sys.argv[0] + '?' + urllib.urlencode({"mode": "rivedi_la7","play": urll,"titolo": nome,"thumb":thumb,"plot":plot.encode('utf-8')})
            xbmcplugin.addDirectoryItem(handle=handle, url=url2,listitem=liStyle, isFolder=False)
        xbmcplugin.endOfDirectory(handle=handle, succeeded=True)
```
Raspberry Pi, OSMC 2018.03-2, Kodi (17.6), plugin.video.rivedila7/addon.py 1.0.0.
Spero possa essere d'aiuto.
A presto

**Comment by Testato** [comment]
Yep, é un problema saltuario perché a volte sbagliano quando aggiungono contenuti.
Nel mio fork oltre ad aggiungere altre funzionalità ho anche inserito un controllo per tale evenienza quindi non si blocca mai.
https://github.com/Testato/plugin.video.rivedila7

**Comment by tpwrm** [comment]
Visto, risolto dalla 1.3.0.
Grazie
