### ISSUE TITLE
Programmi ondemand

### ISSUE THREAD

**Issue by filo1234** [luivit/plugin.video.rivedila7#45]
Ciao, da quando è stato inserito nei repo kodi i programmi ondemand danno errore:

2021-03-11 20:48:50.828 T:7477    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'text'
                                                   Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.video.rivedila7/addon.py", line 1, in <module>
                                                       from resources.lib import plugin
                                                     File "/home/kodi/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 921, in <module>
                                                       video_programma()
                                                     File "/home/kodi/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 549, in video_programma
                                                       video_programma_landpage()
                                                     File "/home/kodi/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 811, in video_programma_landpage
                                                       get_rows_video_landpage(video_puntate_1r)
                                                     File "/home/kodi/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 840, in get_rows_video_landpage
                                                       titolo=div.find('div',class_='title').text.strip()
                                                   AttributeError: 'NoneType' object has no attribute 'text'
                                                   -->End of Python script error report<--
                                                   
2021-03-11 20:48:50.888 T:7477     INFO <general>: Python interpreter stopped
2021-03-11 20:48:50.897 T:7476    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.rivedila7/?link=https%3a%2f%2fwww.la7.it%2fpinkisgood&mode=tutti_programmi
2021-03-11 20:48:50.906 T:7353    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rivedila7/?link=https%3a%2f%2fwww.la7.it%2fpinkisgood&mode=tutti_programmi) failed
2021-03-11 20:48:53.032 T:7480     INFO <general>: initializing python engine.
2021-03-11 20:48:55.788 T:7480     INFO <general>: NO FIRST VIDEO
2021-03-11 20:48:55.790 T:7353     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2021-03-11 20:48:58.123 T:7480     INFO <general>: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.rivedila7/addon.py): script aborted
2021-03-11 20:48:58.171 T:7480     INFO <general>: Python interpreter stopped
2021-03-11 20:48:58.188 T:7479    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.rivedila7/?link=https%3a%2f%2fwww.la7.it%2four-godfather&mode=tutti_programmi
2021-03-11 20:48:58.189 T:7353    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.rivedila7/?link=https%3a%2f%2fwww.la7.it%2four-godfather&mode=tutti_programmi) failed

**Comment by Testato** [comment]
Grazie, confermo il problema, testato su telefono Android
Avranno cambiato qualcosa in questi giorni perché quando abbiamo pubblicato sul repo funzionava.
Appena ho un attimo lo sistemo

**Comment by Testato** [comment]
Fixed.
https://github.com/luivit/plugin.video.rivedila7/archive/master.zip
