### ISSUE TITLE
Doesn't work anymore 

### ISSUE THREAD

**Issue by Typerwild** [luivit/plugin.video.rivedila7#74]
Hi Testato,

Thanks for this - I love this plug in and use it every week to watch la7. It's amazing. 

I have been using this on my Android TV with no issues but I think the website has changed the plug-in used to stream videos. Now I can get all the way to the video or live stream I want to watch but then get an error which says to check the log.

I reckon this might need some sort of change or update to work. Would you be able to do this? It'd be so well to be able to use it again.

Thanks,

Luigi

**Comment by Testato** [comment]
Ciao Luigi, 

On my android phone the two Live channel and also the two Replay section work regularly. Instead the Programs section not work.
It's same for you ?
May you try also on an Android phone ?

**Comment by Typerwild** [comment]
Hi!
Honestly, best plug in on Kodi ever.
Yes the live functions works fine, it's just the programmes aren't working anymore which is such a shame.
I've tested it on my Android TV, I reckon it would be similar on my phone.
I'm not very good at fixing these things but it would be so good if you knew how to fix it!
Thanks,
Luigi 
 
  On Sun, 5 May 2024 at 12:34, ***@***.***> wrote:   


Ciao Luigi,

On my android phone the two Live channel and also the two Replay section work regularly. Instead the Programs section not work.
It's same for you ?
May you try also on an Android phone ?

**Comment by Testato** [comment]
Sometimes La7 website have temporary glitch, we can wait some days and see if the problem will resolve itself.
Otherwise will be necessary to look at logfile

**Comment by fabpolli** [comment]
Hi,
  same problem on  Kodi (20.3 (20.3.0) Git:20.3-Nexus). Platform: Linux ARM 32-bit
2023-02-16 19:11:10.250 T:852      info <general>: Using Release Kodi x32
2023-02-16 19:11:10.250 T:852      info <general>: Kodi compiled 2024-01-27 by GCC 12.2.0 for Linux ARM 32-bit version 6.1.74 (393546)
2023-02-16 19:11:10.250 T:852      info <general>: Running on LibreELEC (official): 11.0.6, kernel: Linux ARM 64-bit version 6.1.74
2023-02-16 19:11:10.250 T:852      info <general>: FFmpeg version/source: 4.4.1-Kodi
"Rivedi la 7" section work correctly, other sections like "Programmi" doesn't show list and report this error on log:
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.rivedila7/addon.py): the source file to load is "/storage/.kodi/addons/plugin.video.rivedila7/addon.py"
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17): full python path:
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):   custom python path:
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/plugin.video.rivedila7
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.beautifulsoup4/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.certifi/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.chardet/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.idna/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.inputstreamhelper/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.requests/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.soupsieve/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /storage/.kodi/addons/script.module.urllib3/lib
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):   default python path:
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /usr/lib/python311.zip
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /usr/lib/python3.11
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /usr/lib/python3.11/lib-dynload
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):     /usr/lib/python3.11/site-packages
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17): adding args:
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):  plugin://plugin.video.rivedila7/
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):  3
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):  ?link=https%3a%2f%2fwww.la7.it%2fpropagandalive&mode=tutti_programmi
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17):  resume:false
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.rivedila7/addon.py): entering source directory /storage/.kodi/addons/plugin.video.rivedila7
2024-05-07 10:32:17.275 T:5657    debug <general>: CPythonInvoker(17, /storage/.kodi/addons/plugin.video.rivedila7/addon.py): instantiating addon using automatically obtained id of "plugin.video.rivedila7" dependent on version 3.0.0 of the xbmc.python api
2024-05-07 10:32:17.323 T:852     debug <general>: ------ Window Init (DialogBusy.xml) ------
2024-05-07 10:32:17.520 T:881     debug <general>: PushCecKeypress - received key  b duration 328
2024-05-07 10:32:18.993 T:852     debug <general>: ------ Window Deinit (DialogNotification.xml) ------
2024-05-07 10:32:19.516 T:5657    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'text'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.rivedila7/addon.py", line 5, in <module>
                                                       run(sys.argv)
                                                     File "/storage/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 855, in run
                                                       video_programma()
                                                     File "/storage/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 500, in video_programma

**Comment by Testato** [comment]
```
/plugin.video.rivedila7/resources/lib/plugin.py", line 774, in get_rows_video_landpage_preview
plot = video.find('div', class_='occhiello').text.strip()

```
Probabile hanno cambiato nome di questa classe 
Io ora non ho proprio tempo, provate a sistemare voi 🙂
Guardando i sorgenti della pagina si può capire cosa hanno cambiato

**Comment by Typerwild** [comment]
Ah, Io non saprei da dove iniziare :(

Yahoo Mail: Search, organise, conquer 
 
  On Wed, 8 May 2024 at 5:46, ***@***.***> wrote:   

/plugin.video.rivedila7/resources/lib/plugin.py", line 774, in get_rows_video_landpage_preview
plot = video.find('div', class_='occhiello').text.strip()


Probabile hanno cambiato nome di questa classe
Io ora non ho proprio tempo, provate a sistemare voi 🙂
Guardando i sorgenti della pagina si può capire cosa hanno cambiato

**Comment by Typerwild** [comment]
Thanks,
Will it work on android TV? Or is the plan for the final solution to work on android TV too?
I don't have Kodi on my computer but just for the TV.
Thanks
Luigi
 
 
  On Wed, 8 May 2024 at 13:48, ***@***.***> wrote:   


Hi,
I've created a pull request to solve problem with Programmi section.
Test only on Kodi 20 for Windows and for that section

**Comment by Testato** [comment]
Kodi plugin must work on every OS.
So yes, try it also on Android Tv

**Comment by nicorac** [comment]
@fabpolli your PR works perfectly on Kodi 21 + AndroidTV, thanks 💪🏻

**Comment by Testato** [comment]
Thanks to @fabpolli

**Comment by Testato** [comment]
Thanks to @fabpolli

**Comment by Xwang1976** [comment]
Why the 6.2.1 version of this add on is still not available on the kodi's add on repository?
I'm using kodi under archlinux and I'm not able anymore to see the programs

**Comment by Typerwild** [comment]
Hi @Testato - I agree with the comment just above. I can't get to download this new version anywhere and I tried to get Kodi to look at the repo but it doesn't seem to like any of the links I've given Kodi so it doesn't find the zip directly and because it's on my android TV I can't download a zip separately and then point Kodi to it

**Comment by Testato** [comment]
I need to post the new version to Kodi repo and wait for it approval. It need time and now i do not have it.
I do not know if also other people over me can submit the update to kodi repo.

Meanwhile this is the link to.the zip, i use a downloader program on the Firestick to download it and after I install the .zip from kodi
https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

**Comment by Xwang1976** [comment]
> I need to post the new version to Kodi repo and wait for it approval. It need time and now i do not have it. I do not know if also other people over me can submit the update to kodi repo.
> 
> Meanwhile this is the link to.the zip, i use a downloader program on the Firestick to download it and after I install the .zip from kodi https://github.com/luivit/plugin.video.rivedila7/archive/refs/heads/master.zip

Can I use it for linux too? If yes, it will be automatically update later when the add on reaches the repository or should I do something too go back to the "automatic update" mode ?

**Comment by Testato** [comment]
Yes, kodi plugins are crossplatform.
Yes it will be automatically updated
