### ISSUE TITLE
Voce Programmi -> Error

### ISSUE THREAD

**Issue by writetome1** [luivit/plugin.video.rivedila7#76]
La voce del menù programmi non funziona correttamente: dopo aver mostrato correttamente la lista dei programmi va in errore alla succesiva selezione del singolo programma

Da Kodi log:
2024-11-11 17:11:56.209 T:24299   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'text'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.rivedila7/addon.py", line 5, in <module>
                                                       run(sys.argv)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 855, in run
                                                       video_programma()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 500, in video_programma
                                                       video_programma_landpage()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 748, in video_programma_landpage
                                                       get_rows_video_landpage_preview(video_iniziale)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.rivedila7/resources/lib/plugin.py", line 774, in get_rows_video_landpage_preview
                                                       plot = video.find('div', class_='occhiello').text.strip()
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: 'NoneType' object has no attribute 'text'
                                                   -->End of Python script error report<--

**Comment by Testato** [comment]
Confermato
Grazie

**Comment by Testato** [comment]
Se sei in grado di risolverlo tu, basta che mi mandi la soluzione ed è risolto 🙂

**Comment by writetome1** [comment]
Se avessi il sorgente forse potrei provarci ....

**Comment by Testato** [comment]
???
Sei su Github baby 😅

**Comment by writetome1** [comment]
Ciao ... non direi che  all'indirizzo fornito c'è il  source ... sono io che mi sbaglio ? comunque spero in un rapido aggiornameto ...  grazie

**Comment by writetome1** [comment]
Ciao, grazie, ho inserito la correzione nel  source "C:\Users\write\AppData\Roaming\Kodi\addons\plugin.video.rivedila7\resources\lib\plugin.py" l'ho provato con qualche voce ed è OK ! 😃  formidabile  !

**Comment by 24mu13** [comment]
Allo stato attuale la versione 6.2.1 (che pure non sta nei repo ufficiali) non fa nemmeno vedere la lista dei programmi!

Soltanto mostra i due programmi aggiunti manualmente:
```python
        # Prog aggiunti manualmente
        programmi = {
            'LA MALA EDUCAXXXION 2': {
                'url': '/la-mala-educaxxxion',
                'img': 'https://kdam.iltrovatore.it/p/103/sp/10300/thumbnail/entry_id/0_j0z82ps2/version/100001/type/5/width/600/height/360/quality/100/name/0_j0z82ps2.jpg'
            },
            'NON CLASSIFICATI': {
                'url': '/non-classificati',
                'img': '',
            },
        }
```

**Comment by Testato** [comment]
Grazie della segnalazione, 
Anche l'attuale versione 6.2.0 presente sul Repo kodi fa uguale. 
Aspettiamo domani per vedere se è un problema temporaneo del sito La7, altrimenti apri per favore una nuova Issue che è una cosa diversa da questa issue
